# this is also a list of the available languages from google translate's api
lang_dict = { 
    "[fr]": "fr",
    "[afrikaans]" :	"af",
    "[albanian]" : "sq",
    "[amharic]" : "am",
    "[arabic]" 	: "ar",
    "[armenian]" :"	hy",
    "[azerbaijani]" :"az",
    "[basque]" : "eu",
    "[belarusian]" : "be",
    "[bengali]" : "bn",
    "[bosnian]" : "bs",
    "[bulgarian]" : "bg",
    "[catalan]" : "ca",
    "[cebuano]" : "ceb",
    "[chinese simplified]" : "zh-cn", # or zh (bcp-47)
    "[simplified chinese]" : "zh-cn",
    "[chinese traditional]" : "zh-tw", # (bcp-47)
    "[traditional chinese]" : "zh-tw", 
    "[corsican]" : 	"co",
    "[croatian]" : 	"hr",
    "[czech]" : 	"cs",
    "[danish]" : 	"da",
    "[dutch]" : 	"nl",
    "[english]" : 	"en",
    "[esperanto]" : "eo",
    "[estonian]" : 	"et",
    "[finnish]" : 	"fi",
    "[french]" : 	"fr",
    "[frisian]" : 	"fy",
    "[galician]" : 	"gl",
    "[georgian]" : 	"ka",
    "[german]" : 	"de",
    "[greek]" : 	"el",
    "[gujarati]" : 	"gu",
    "[haitian creole]" : "ht",
    "[hausa]" : 	"ha",
    "[hawaiian]" : 	"haw", #(iso-639-2)
    "[hebrew]" : 	"he",  #or iw
    "[hindi]" : 	"hi",
    "[hmong]" : 	"hmn", #(iso-639-2)
    "[hungarian]" : "hu",
    "[icelandic]" : "is",
    "[igbo]" : 	"ig",
    "[indonesian]" : "id",
    "[irish]" : 	"ga",
    "[italian]" : 	"it",
    "[japanese]" : 	"ja",
    "[javanese]" : 	"jv",
    "[kannada]" : 	"kn",
    "[kazakh]" : 	"kk",
    "[khmer]" : 	"km",
    "[kinyarwanda]" : "rw",
    "[korean]" : 	"ko",
    "[kurdish]" : 	"ku",
    "[kyrgyz]" : 	"ky",
    "[lao]" : 	"lo",
    "[latin]" : 	"la",
    "[latvian]" : 	"lv",
    "[lithuanian]" : 	"lt",
    "[luxembourgish]" : 	"lb",
    "[macedonian]" : 	"mk",
    "[malagasy]" : 	"mg",
    "[malay]" : 	"ms",
    "[malayalam]" : 	"ml",
    "[maltese]" : 	"mt",
    "[maori]" : 	"mi",
    "[marathi]" : 	"mr",
    "[mongolian]" : "mn",
    "[myanmar]" : "my",
    "[burmese]" : "my",
    "[nepali]" : "ne",
    "[norwegian]" : "no",
    "[nyanja]" : 	"ny",
    "[chichewa]" : 	"ny",
    "[odia ]" : 	"ps", # or pashto
    "[oriya]" : 	"ps",
    "[persian]" : 	"fa",
    "[polish]" : 	"pl",
    "[portuguese]" : "pt",
    "[punjabi]" : 	"pa",
    "[romanian]" : 	"ro",
    "[russian]" : 	"ru",
    "[samoan]" : 	"sm",
    "[scots gaelic]" : 	"gd",
    "[serbian]" : 	"sr",
    "[sesotho]" : 	"st",
    "[shona]" : 	"sn",
    "[sindhi]" : 	"sd",
    "[sinhala]" :	"si",
    "[sinhalese]: " : "si",
    "[slovak]" : 	"sk",
    "[slovenian]" : "sl",
    "[somali]" : 	"so",
    "[spanish]" : 	"es",
    "[sundanese]" : "su",
    "[swahili]" : 	"sw",
    "[swedish]" : 	"sv",
    "[tagalog]" :	"tl",
    "[filipino]" : "tl",
    "[tajik]" : 	"tg",
    "[tamil]" : 	"ta",
    "[tatar]" : 	"tt",
    "[telugu]" : 	"te",
    "[thai]" : 	"th",
    "[turkish]" : 	"tr",
    "[turkmen]" :	"tk",
    "[ukrainian]" : "uk",
    "[urdu]" : 	"ur",
    "[uyghur]" : 	"ug",
    "[uzbek]" : 	"uz",
    "[vietnamese]" : "vi",
    "[welsh]" : 	"cy",
    "[xhosa]" : 	"xh",
    "[yiddish]" : 	"yi",
    "[yoruba]" : 	"yo",
    "[zulu]" : 	"zu"
    }


